name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    
    - name: yarn install
      run: |
        yarn install 
    
    - name: yarn build
      run: |
        yarn build
    # TODO repair this line
    - name: Add remote origin
      env:
          KEY: ${{ secrets.HEROKU_API_KEY }}
          APP: ${{ secrets.HEROKU_APP }}
      run: |
        git remote add heroku https://heroku:$KEY@git.heroku.com/$APP.git

    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f